on:
    push:
        branches: [ master ]
    
jobs:
    deploy:
        runs-on: self-hosted
    
        strategy: 
            matrix:
              node-version: [14.x]
            
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
                node-version: ${{ matrix.node-version }}
          - run: 'echo "$DOTENV" > .env'
            env:
                DOTENV: ${{secrets.DOTENV}}
          - run: npm install
          - run: pm2 restart spotifyinfo
